#   _          _                _         _   _
#  | |    __ _(_)_   ___   _   / \  _   _| |_| |__
#  | |   / _` | \ \ / / | | | / _ \| | | | __| '_ \
#  | |__| (_| | |\ V /| |_| |/ ___ \ |_| | |_| | | |
#  |_____\__,_|_| \_/  \__, /_/   \_\__,_|\__|_| |_|
#                      |___/
#
# Author: Daniel Meinicke (Laivy)
# Support: https://laivy.codes/discord?ref=LaivyAuth
#

# Sets the debug state of the plugin.
# If true, the plugin will send detailed logs that may
# be useful for developers to see exactly what's happening at the plugin.
debug: false

# When this option is enabled, nicknames with the same characters but differing
# in case (uppercase or lowercase) will be considered identical.
#
# For example, if there is an account created with the nickname "Laivy"
# attempting to connect with the nickname "laivy":
# The plugin will prevent the user from proceeding with connection and authentication,
# ordering the player to change the nickname to "Laivy" again.
#
# The native notchian (vanilla) minecraft servers disable this as default.
# Keeping this as true if strongly recommended then, it avoids a lot of issues.
#
# If you want to change this, it's strongly recommended to reset the plugin's database and
# all the server's player list first, to avoid players losing their accounts.
case-sensitive-nicknames: true

# Stops the server if an error occurs while loading the plugin.
# You don't want your server running without the authentication system, trust me.
stop-server-if-fails: true

# This option stores all the database into the RAM on load-up the server.
# It's not recommended for servers with a high number of players (like +300K).
# When false, this option takes more take to authenticate the users and retrieve
# some other information because it will need to load it from the disk first.
buffered-database: true

unauthenticated:
  movement: false
  visible: true
  timeout: 120 # In seconds
  blindness: true

updates:
  # Sets the time in minutes that the plugin should check for new mappings and plugin updates.
  # Leave it "-1" if you want to disable the update checks
  check: 60

  # Sets if the plugin should be automatically updated if there's a new available version.
  # Automatic updates provide convenience but may introduce changes unexpectedly.
  # Note: This setting is ignored if 'check' is set to false.
  auto: true

premium-automatic-auth:
  # When enabled, premium users will not need to authenticate using commands.
  # The plugin differentiates between premium and cracked users as follows:
  # 1. The client attempts to connect to the server.
  # 2. The server sends a message prompting the client to reconnect.
  # 3. The player must reconnect for verification.
  #    - If the verification process fails, the client is considered a cracked user and must enter a password.
  #    - If the verification process is successful, the player is considered a premium user and will not need to enter a password for future logins, provided they use a premium account.
  # Note this feature will make the server online-mode=true, but cracked users still can join.
  enabled: true
  premium_requires_login_temp: true # This is just for debug and will be replaced later!

whitelist:
  # If false, cracked users (those who are using unauthorized copies of the game) will not be able to join the server.
  # This helps prevent unauthorized access and maintain server integrity.
  # Useful when you need to block cracked users temporarily or just want to use
  # our amazing and wonderful authentication plugin without necessarily having cracked users.
  # For api purposes as example.
  #
  # To use this feature, the 'premium-automatic-auth' must be enabled.
  allow-cracked-users: true

  # Here you can block some protocol versions to join the server.
  # That will prevent clients from connecting with unwanted client versions.
  # Here's the full versions list: https://wiki.vg/Protocol_version_numbers
  block-protocol-versions:
  #  - 767 # This blocks the 1.21
  #  - 766 # This blocks the 1.20.6 and 1.20.5

captcha:

email:
  # Defines if the players should be forced to enter an e-mail to authenticate,
  # you should consider change this option to 'true', it's safer, and you'll have
  # a lead to announce your marketing offers :)
  required: false

oraxen:
  # This configuration will make Oraxen only send the texture to the player after
  # authentication
  sends-pack-only-when-auth: true